---
title: "README"
author: "JIaqi Ni, Stephanie K. Nishi, Nancy Babio, Clara Belzer, Jesús Vioque, Dolores Corella, Javier Hernando-Redondo, Josep Vidal, Isabel Moreno-Indias, Laura Compañ-Gabucio, Oscar Coltell, Montse Fitó, Estefanía Toledo, Dong D. Wang, Francisco J. Tinahones & Jordi Salas-Salvadó"
date: "2024-04-02"
output: html_document
---

## Olive oil consumption, gut microbiota, and changes in cognitive function in older adults at high risk of cognitive decline

This repository contains the analysis programs for the project that assess the interplay between olive oil consumption, gut microbiota and changes in cognitive function in 656 older adults from the [PREDIMED-Plus Study](https://www.predimedplus.com/en/). All analyses were performed in R version 4.3.1. To run the full pipeline place the obtained data files in the DATA folder. The script will create multiple folders and files inside the Output folder containing tables, figures and text files containing the analysis results and other supporting information. If need be, analysis script files can also be run independently without the need to run the whole pipeline.

### Directory structure

````
Olive oil-Gut microbiota-Cognitive function/
├── README.Rmd               # Study overview
├── DATA                     # Input folder for the data to be analyzed
├── Output                   # Ouput folder for analysis results
└── Scripts 
    ├── 0_data_prep.r                     # Script for preparing the original raw data for downstream analyses
    ├── 1_descriptives.r                  # Script for creating descriptive statistics
    ├── 2_oliveoil_cognition.r            # Script for analyzing the associations between olive oil consumption and changes in cognitive function             
    ├── 3_alpha_oliveoil.r                # Script for analyzing alpha-diversity associations with olive oil consumption
    ├── 4_beta_oliveoil.r                 # Script for analyzing beta-diversity associations with olive oil consumption
    ├── 5_taxa_oliveoil.r                 # Script for analyzing genus-specific associations with olive oil consumption
    ├── 6_microbiome_cognition.r          # Script for analyzing associations of identified olive oil-associated gut microbiota signatures with changes in cognitive function
    └── 7_mediation.r                     # Script for analyzing the mediating role of the gut microbiota in the association between olive oil consumption and changes in cognitive function
```` 

### sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=es_ES.UTF-8       LC_NUMERIC=C               LC_TIME=es_ES.UTF-8        LC_COLLATE=es_ES.UTF-8     LC_MONETARY=es_ES.UTF-8    LC_MESSAGES=es_ES.UTF-8   
 [7] LC_PAPER=es_ES.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=es_ES.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Madrid
tzcode source: system (glibc)

attached base packages:
[1] grid      stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggside_0.2.3                    ggExtra_0.10.1                  RColorBrewer_1.1-3              openxlsx_4.2.5.2                tableone_0.13.2                
 [6] diagram_1.6.5                   shape_1.4.6                     glue_1.6.2                      HIMA_2.2.1                      glmnet_4.1-8                   
[11] ncvreg_3.14.1                   lmtest_0.9-40                   zoo_1.8-12                      mediation_4.5.0                 sandwich_3.0-2                 
[16] mvtnorm_1.2-4                   Matrix_1.6-1.1                  MASS_7.3-60                     labelled_2.12.0                 summarytools_1.0.1             
[21] haven_2.5.4                     phyloseq_1.46.0                 modelsummary_1.4.3              lubridate_1.9.3                 forcats_1.0.0                  
[26] stringr_1.5.1                   purrr_1.0.2                     readr_2.1.4                     tidyr_1.3.0                     tibble_3.2.1                   
[31] tidyverse_2.0.0                 ggalluvial_0.12.5               Maaslin2_1.16.0                 sjPlot_2.8.15                   cowplot_1.1.1                  
[36] gridExtra_2.3                   ggsignif_0.6.4                  ggpubr_0.6.0                    dplyr_1.1.4                     patchwork_1.1.3                
[41] vegan_2.6-4                     lattice_0.21-9                  permute_0.9-7                   scater_1.30.1                   scuttle_1.12.0                 
[46] miaViz_1.10.0                   ggraph_2.1.0                    ggplot2_3.4.4                   miaTime_0.1.21                  mia_1.11.1                     
[51] MultiAssayExperiment_1.28.0     TreeSummarizedExperiment_2.10.0 Biostrings_2.70.1               XVector_0.42.0                  SingleCellExperiment_1.24.0    
[56] SummarizedExperiment_1.32.0     Biobase_2.62.0                  GenomicRanges_1.54.1            GenomeInfoDb_1.38.1             IRanges_2.36.0                 
[61] S4Vectors_0.40.2                BiocGenerics_0.48.1             MatrixGenerics_1.14.0           matrixStats_1.1.0              

loaded via a namespace (and not attached):
  [1] sjmisc_2.8.9                nnet_7.3-19                 TH.data_1.1-2               vctrs_0.6.5                 digest_0.6.33               pcaPP_2.0-3                
  [7] ggrepel_0.9.4               bayestestR_0.13.1           HDMT_1.0.5                  magick_2.8.1                reshape2_1.4.4              httpuv_1.6.9               
 [13] foreach_1.5.2               qvalue_2.34.0               withr_2.5.2                 xfun_0.41                   ggfun_0.1.3                 ellipsis_0.3.2             
 [19] survival_3.5-7              memoise_2.0.1               ggbeeswarm_0.7.2            linprog_0.9-4               MatrixModels_0.5-3          emmeans_1.8.9              
 [25] systemfonts_1.0.5           tidytree_0.4.5              DEoptimR_1.1-3              Formula_1.2-5               promises_1.2.0.1            httr_1.4.5                 
 [31] rstatix_0.7.2               rhdf5filters_1.14.1         rhdf5_2.46.1                rstudioapi_0.14             miniUI_0.1.1.1              generics_0.1.3             
 [37] base64enc_0.1-3             mitools_2.4                 zlibbioc_1.48.0             ScaledMatrix_1.10.0         polyclip_1.10-6             ggeffects_1.3.2            
 [43] GenomeInfoDbData_1.2.11     SparseArray_1.2.2           xtable_1.8-4                ade4_1.7-22                 doParallel_1.0.17           evaluate_0.20              
 [49] S4Arrays_1.2.0              hms_1.1.3                   hommel_1.6                  irlba_2.3.5.1               colorspace_2.1-0            getopt_1.20.4              
 [55] magrittr_2.0.3              later_1.3.0                 viridis_0.6.4               ggtree_3.10.0               robustbase_0.99-1           SparseM_1.81               
 [61] DECIPHER_2.30.0             survey_4.2-1                Hmisc_5.1-1                 pillar_1.9.0                nlme_3.1-163                performance_0.10.8         
 [67] iterators_1.0.14            decontam_1.22.0             compiler_4.3.1              beachmat_2.18.0             stringi_1.8.2               biomformat_1.30.0          
 [73] minqa_1.2.6                 plyr_1.8.9                  crayon_1.5.2                abind_1.4-5                 gridGraphics_0.5-1          modelr_0.1.11              
 [79] graphlayouts_1.0.2          bit_4.0.5                   rapportools_1.1             biglm_0.9-2.1               codetools_0.2-19            multcomp_1.4-25            
 [85] BiocSingular_1.18.0         mime_0.12                   multtest_2.58.0             splines_4.3.1               scalreg_1.0.1               Rcpp_1.0.11                
 [91] quantreg_5.97               sparseMatrixStats_1.14.0    lars_1.3                    knitr_1.42                  blob_1.2.4                  utf8_1.2.4                 
 [97] lme4_1.1-35.1               fs_1.6.3                    checkmate_2.3.1             DelayedMatrixStats_1.24.0   ggplotify_0.1.2             estimability_1.4.1         
[103] tzdb_0.4.0                  lpSolve_5.6.19              svglite_2.1.2               tweenr_2.0.2                pkgconfig_2.0.3             tools_4.3.1                
[109] cachem_1.0.8                RSQLite_2.3.3               viridisLite_0.4.2           rvest_1.0.3                 DBI_1.1.3                   fastmap_1.1.1              
[115] rmarkdown_2.20              scales_1.3.0                hdi_0.1-9                   broom_1.0.5                 coda_0.19-4                 insight_0.19.7             
[121] carData_3.0-5               rpart_4.1.19                farver_2.1.1                tidygraph_1.2.3             mgcv_1.9-0                  foreign_0.8-85             
[127] sjstats_0.18.2              cli_3.6.1                   webshot_0.5.5               lifecycle_1.0.4             bluster_1.12.0              backports_1.4.1            
[133] BiocParallel_1.36.0         timechange_0.2.0            gtable_0.3.4                parallel_4.3.1              ape_5.7-1                   jsonlite_1.8.8             
[139] bitops_1.0-7                kableExtra_1.3.4            bit64_4.0.5                 yulab.utils_0.1.0           BiocNeighbors_1.20.0        zip_2.2.2                  
[145] lazyeval_0.2.2              shiny_1.7.4                 pander_0.6.5                htmltools_0.5.4             sjlabelled_1.2.0            optparse_1.7.3             
[151] tcltk_4.3.1                 RCurl_1.98-1.13             treeio_1.26.0               boot_1.3-28                 igraph_1.5.1                R6_2.5.1                   
[157] fdrtool_1.2.17              cluster_2.1.4               Rhdf5lib_1.24.0             aplot_0.2.2                 nloptr_2.0.3                DirichletMultinomial_1.44.0
[163] DelayedArray_0.28.0         tidyselect_1.2.0            vipor_0.4.5                 htmlTable_2.4.2             conquer_1.3.3               ggforce_0.4.1              
[169] xml2_1.3.3                  car_3.1-2                   rsvd_1.0.5                  munsell_0.5.0               tables_0.9.17               pryr_0.1.6                 
[175] data.table_1.14.8           htmlwidgets_1.6.1           rlang_1.1.2                 ggnewscale_0.4.9            fansi_1.0.5                 beeswarm_0.4.0      

### Others
Typical install time on a "normal" desktop computer: aprox. 3 mins.

Expected run time for demo on a "normal" desktop computer: aprox. 30 mins. 